version: '3'

services:
       mongo:
          image: mongo
          volumes:
               - mongo-db:/var/data
          ports:
               - "27017:27017"

       express:
            build: .
            volumes:
                - .:/app
            ports:
                - "80:3000"
            links:
                - mongo
volumes:
    mongo-db:
